name: CI-Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sast-scan:
    runs-on: ubuntu-latest
    environment: common
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v4.2.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=basiuktv
            -Dsonar.projectKey=BasiukTV_pygoat

  docker-build:
    if: false # Disabling this while working on other things
    runs-on: ubuntu-latest
    environment: common
    env:
      # Currently uses Docker Hub, so no registry info is needed
      # DOCKER_REGISTRY: YOUR_REGISTY
    
      DOCKER_USER: ${{ vars.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.11'

#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
            
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        uses: docker/login-action@v3.4.0
        with:

          # Currently uses Docker Hub, so no registry info is needed
          # registry: YOUR_REGISTY

          # Username used to log in to the Docker registry
          username: ${{ env.DOCKER_USER }}
          # Password or personal access token used to log in to the Docker registry
          password: ${{ env.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.DOCKER_USER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.run_id }}

      - name: Scan image with Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations
          image: ${{ env.DOCKER_USER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.run_id }}
          only-severities: critical,high
          sarif-file: docker-scout-sarif.output.json
          summary: true

          # Below being set to true will fail the run if vulnerabilities are found
          # But as this project is focused on finding the vulnerabilities, not fixing them, we set it to false
          exit-code: false

      - name: Upload Docker Scout SARIF result
        if: ${{ always() }} # Run this even if Docker Scout scanning resulted in failure
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: docker-scout-sarif.output.json
